#!/usr/bin/env bash
# Displays PID along with process name of process whose name contain the word bash
pgrep -l bash | while read -r pid process_name; 
do
	echo "PID: $pid - Process Name: $process_name"
done
