#!/usr/bin/env bash
# Use Kill command to stop a process
pid=$(pgrep -f "4-to_infinity_and_beyond")

if [ -n "$pid" ];
then
	kill "$pid"
	echo "Terminated"
else
	echo "Process 4-to_infinity_and_beyond not found."
fi
