#!/usr/bin/env bash
# This script loops from 1 to 10 and is displaying various iteratons
i=1
while [ $i -le 10 ]
do
	if [ $i -lt 4 ]
	then
		echo "Best school"
	elif [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
