#!/usr/bin/env bash
# Script that checks for the existence of the school file and provides details
if [ -e "school" ];
then
	echo "school file exists"
	
	if [ -f "school" ];
	then
	
		if [ ! -s "school" ];
		then
			echo "school file is empty"
		else
			echo "school file is not empty"
		fi
		echo "school file exists"
		echo "school is a regular file"

	elif [ -d "school" ];
	then
		echo "school file exists"
		echo "school is a directory"
	else
		echo "school file exists"
	fi

else
	echo "school file does not exist"
fi
