#!/usr/bin/env bash
# Script that checks for the existence of the school file and provides details
if [ -e "school" ];
then
	echo "school file exists"
	
	if [ -f "school" ];
	then
		echo "school is a regular file"

		if [ ! -s "school" ];
		then
			echo "school file is empty"
		else
			echo "school file is not empty"
	fi

	elif [ -d "school" ];
	then
		echo "school is a directory"
	fi

else
	echo "school file does not exist"
fi
